### ISSUE TITLE
App crashes!

### ISSUE THREAD

**Issue by Elton3821** [BlackVikingPro/arescrypt#1]
i dont know whats happening i have done everything how it should be and also connected the .php file with my database also installed PHP 7.0 version on my webhosting but when i release my app and open it it just throw a .dat file but after few seconds app will crash giving me the below problems (please take a look at my screenshots):

first screen: http://prntscr.com/hruuj7
second screen: http://prntscr.com/hruuxx

i hope you will reply as soon as you can i really need a solution in this problem! thank you!

**Comment by BlackVikingPro** [comment]
Hey there, could you try to go into the **Configuration.cs** file and change the variable **debudMode** to **true**. That should give you more insight onto what exactly the problem is - and once you've done that, just post the error message here please.
